#!/bin/bash

# Podsock - Simple wrapper for podman that adds new +flags
# that are shorthand for common operations

: ${PODSOCK_UID:="1000"}
: ${PODSOCK_RTDIR:="/run/user/${PODSOCK_UID}"}

#command -v podman >/dev/null 2>&1 || { echo "Error: podman is required but not installed" && exit 1; }

COMMAND_LINE="podman "

# Loop through args, checking for +flags
for arg in "$@"; do
    if [[ "$arg" == +* ]]; then
        # Remove the leading + and process each character
        flags="${arg:1}"
        for (( i=0; i<${#flags}; i++ )); do
            case "${flags:$i:1}" in
                # Wayland
                w)
                    [[ -z "${WAYLAND_DISPLAY}" ]] && { echo "Error: WAYLAND_DISPLAY not set"; exit 1; }
                    [[ -z "${XDG_RUNTIME_DIR}" ]] && { echo "Error: XDG_RUNTIME_DIR not set"; exit 1; }
                    [[ -S "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] || { echo "Error: Wayland socket not found at ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}"; exit 1; }
                    COMMAND_LINE+="\
                      --env=WAYLAND_DISPLAY=${WAYLAND_DISPLAY} \
                      --volume=${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${PODSOCK_RTDIR}/${WAYLAND_DISPLAY}:ro \
                      "
                    ;;
                # SSH Agent
                s)
                    [[ -z "${SSH_AUTH_SOCK}" ]] && { echo "Error: SSH_AUTH_SOCK not set"; exit 1; }
                    [[ -S "${SSH_AUTH_SOCK}" ]] || { echo "Error: SSH socket not found at ${SSH_AUTH_SOCK}"; exit 1; }
                    COMMAND_LINE+="\
                      --env=SSH_AUTH_SOCK=${PODSOCK_RTDIR}/ssh-agent.socket \
                      --volume=${SSH_AUTH_SOCK}:${PODSOCK_RTDIR}/ssh-agent.socket:ro \
                      "
                    ;;
                # Graphics
                g)
                    [[ -d /dev/dri ]] || { echo "Error: /dev/dri not found"; exit 1; }
                    COMMAND_LINE+=" --device /dev/dri"
                    ;;
                # Network
                n)
                    COMMAND_LINE+=" --network=host --cap-add=NET_RAW,NET_ADMIN,NET_BIND_SERVICE"
                    ;;
                # Debug
                d)
                    COMMAND_LINE+=" --cap-add=SYS_PTRACE,PERFMON --security-opt seccomp=unconfined"
                    ;;
                *)
                    echo "Error: Unknown flag: +${flags:$i:1}"
                    exit 1
                    ;;
            esac
        done
    # In the case of run or create subcommands, add the XDG_RUNTIME_DIR env var
    elif [[ "$arg" == "run" ]] || [[ "$arg" == "create" ]]; then
        COMMAND_LINE+=" $arg --userns=keep-id:uid=${PODSOCK_UID} --env=XDG_RUNTIME_DIR=${PODSOCK_RTDIR}"
    else
        COMMAND_LINE+=" $arg"
    fi
done

echo "$COMMAND_LINE" | tr -s ' '
